---
dependency:
  name: galaxy
driver:
  name: docker
lint: |  
  set -e
  yamllint .   
platforms:  
  - name: centos7
    image: pycontribs/centos:7
    pre_build_image: true  
provisioner:
  name: ansible
verifier:
  name: ansible
